### ISSUE TITLE
docker-engine package not found?

### ISSUE THREAD

**Issue by smrgit** [NCI-GDC/gdc-dnaseq-cwl#40]
when I run this command from the README:
```
sudo aptitude install apt-transport-https ca-certificates docker-engine htop libffi-dev libssl-dev nodejs python-dev virtualenvwrapper
```
I get the following back:
```
Couldn't find any package whose name or description matched "docker-engine"
```
should I try, for example, ``docker.io`` instead?  ( I am trying this from an Ubuntu 14.04 LTS Google Compute Engine VM).
thanks,
Sheila

**Comment by jeremiahsavage** [comment]
Thank you for finding this issue, Sheila. The `docker.io` package should work. Additionally, I have added command 3 to step 1 of the Readme to enable installation of `docker-engine` provided by docker.com, which is the package we use.

https://github.com/NCI-GDC/gdc-dnaseq-cwl/commit/99c19653ec18886502ee24eb08bf4f5a67547c13
