### ISSUE TITLE
Cannot parametrize step bam_reheader of workflow transform.cwl

### ISSUE THREAD

**Issue by hcraT** [NCI-GDC/gdc-dnaseq-cwl#54]
Hi,
I'm using the realignment pipeline to align some genomes to the reference hg19. I discovered that the step bam_reheader changes the header of the bam to the grch38 reference header that is not passed as a parameter but uses instead a file that is present in the Docker image whose value is hardcoded in the python script that apply the change.
Given that the pipeline accepts a reference genome as parameter I suppose that the pipeline has been concieved to be generic and the problem got unnoticed because you use a unique genome version. Is this correct? In case would make sense to add such file as a parameter?

Thanks,
Best regards.

**Comment by kmhernan** [comment]
What you are stating makes sense if it were supposed to be generic, which I don't believe it is. Should this even be public @jeremiahsavage

**Comment by jeremiahsavage** [comment]
Hi @hcraT,

Thanks for testing the pipeline. This is something that would be good to make generic.

A newer version of the workflow in testing passes the fasta dictionary file as input to the workflow, so this shouldn't be too difficult. The code is here: https://github.com/NCI-GDC/bam_reheader/tree/master/bam_reheader

I'll probably be able to get that working within a few weeks.

There's no PHI in this repo / docker, so it's okay to be public.

**Comment by purplepeopleeater** [comment]
Github issues are not routinely monitored by the GDC team. For questions to the GDC please contact the GDC Help Desk (support@nci-gdc.datacommons.io).
--GDC Support Team
