### ISSUE TITLE
Secondary file in output of picard_sortsam not defined

### ISSUE THREAD

**Issue by bogdang989** [NCI-GDC/gdc-dnaseq-cwl#55]
Hi @jeremiahsavage ,
I am Bogdan from SevenBridges. We are currently testing DNA-Seq Workflow as a part of GA4GH challenge. There is one minor thing that we had to edit to make it run if we delete intermediate files that are no longer needed during execution to save up on storage. 
Secondary file on output of picard_sortsam.cwl is not defined so it is deleted and metrics tools fail as they can't locate it.
The fix would be just to add secondary file as it is now defined in output of picard_buildbamindex.cwl:

> `outputs:
>   - id: SORTED_OUTPUT
>     type: File
>     format: "edam:format_2572"
>     outputBinding:
>       glob: $(inputs.OUTPUT)
>     secondaryFiles:
>     - ^.bai`

**Comment by jeremiahsavage** [comment]
Thanks for the report. Fixed with
https://github.com/NCI-GDC/gdc-dnaseq-cwl/commit/1f09727fd23ae0f12912a8301949ce654d996651
